name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  id-token: write
  pull-requests: write
  issues: write

jobs:
  Build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Build
        run: echo "Build Completed !"
        
  Test:
    runs-on: [ubuntu-latest]
    needs: Build
    steps:
      - name: Test
        run: echo "Test Completed"
          
  Deploy-Dev:
    runs-on: [ubuntu-latest]
    needs: [Build, Test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy Dev
        run: echo "Dev Deployed"

  Deploy-Qa:
    runs-on: [ubuntu-latest]
    environment: qa
    needs: [ Deploy-Dev ] 
    steps:
      - name: Deploy QA
        run: echo "QA Deployed"

  Deploy-Uat:
    runs-on: [ubuntu-latest]
    needs: [Build, Test]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy Uat
        run: echo "UAT Deployed"

  Deploy-Prod:
    runs-on: [ubuntu-latest]
    environment: prod
    needs: [ Deploy-Uat ]
    steps:
      - name: Deploy Prod
        run: echo "prod Deployed"
