name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  Build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Build
        run: echo "Build Completed"
        
  Test:
    runs-on: [ubuntu-latest]
    needs: Build
    steps:
      - name: Test
        run: echo "Test Completed"
          
  Deploy-Dev:
    runs-on: [ubuntu-latest]
    needs: Build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy Dev
        run: echo "Dev Deployed"
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: prakash0610
          minimum-approvals: 1
          issue-title: "Deply to QA"
          issue-body: "Please approve or deny the deployment of qa"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''


  Deploy-Qa:
    runs-on: [ubuntu-latest]
    needs: [Build, Test, Deploy-Dev ]
    if: github.ref == 'refs/heads/main' 
    steps:
      - name: Deploy QA
        run: echo "QA Deployed"

  Deploy-Uat:
    runs-on: [ubuntu-latest]
    needs: Build
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Deploy Uat
        run: echo "UAT Deployed"
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: prakash0610
          minimum-approvals: 1
          issue-title: "Deploy to Prod"
          issue-body: "Please approve or deny the deployment of prod"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

  Deploy-Prod:
    runs-on: [ubuntu-latest]
    needs: [Build, Test, Deploy-Uat ]
    if: github.ref == 'refs/heads/master' 
    steps:
      - name: Deploy Prod
        run: echo "prod Deployed"
